[package]
name = "hyprpaper-picker"
authors = ["aragami3070 <smirnov17612@gmail.com>"]
repository = "https://github.com/aragami3070/hyprpaper-picker"
version = "0.1.0"
edition = "2024"

[dependencies]
rstest = "0.26.1"
clap = { version = "4.5.39", features = ["derive"] }
rand = "0.9.2"
